# TODO: background mode
# TODO: CMake by Repo
# ~/CSMI/GitHub/monitoring_interface/docker# time docker build -t csmi_nest_vue:test .

# syntax=docker/dockerfile:1
FROM ubuntu:20.04
LABEL maintainer "rudnick@uni-trier.de"
RUN mkdir /work
WORKDIR /work
COPY ./ /work

ENV TICS_PER_MS=1000
ENV TICS_PER_STEP=100
ENV TZ=Europe/Amsterdam

ARG DEBIAN_FRONTEND=noninteractive
