[package]
name = "proc-lore"
version = "0.1.0"
authors = ["Nick Rudnick <rudnick@uni-trier.de>"]
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
page_size = { version = "0.4.2" }
